jobs:
  build:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
  install:
      executor:
        name: node/default
        tag: '13.14'
      steps:
        - checkout
        - node/install-packages
        - run:
            command: npm install
          


version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - install
      - build
      - node/test
